theme: jekyll-theme-cayman
show_logo: true
show_title: false
title: ISIQuiz
description: Progetto accademico per il corso Paradigmi di Programmazione e Sviluppo (PPS). Applicazione per gamificare il ripasso pre-esame degli argomenti universitari.
show_downloads: false
github:
  zip_url: https://github.com/ISIQuiz/PPS-22-isiquiz/releases
  tar_url: https://github.com/ISIQuiz/PPS-22-isiquiz/releases
