theme: jekyll-theme-cayman
show_logo: true
show_title: false
title: ISIQuiz
show_downloads: false
github:
  zip_url: https://github.com/ISIQuiz/PPS-22-isiquiz/releases
  tar_url: https://github.com/ISIQuiz/PPS-22-isiquiz/releases
defaults:
  -
    scope:
      path: ""
    values:
      description: Progetto accademico per il corso Paradigmi di Programmazione e Sviluppo (PPS). Applicazione per gamificare il ripasso pre-esame degli argomenti universitari.
  -
    scope:
      path: "en"
    values:
      description: Academic Project for Paradigms of Programming and Development (PPS) Course. <br>Application to gamify the pre-exam review of the main topics of a university course.
