theme: jekyll-theme-cayman
show_logo: true
show_title: false
title: ISIQuiz
show_downloads: false
github:
  zip_url: https://github.com/ISIQuiz/PPS-22-isiquiz/releases
  tar_url: https://github.com/ISIQuiz/PPS-22-isiquiz/releases
defaults:
  -
    scope:
      path: ""
    values:
      description: Applicazione per gamificare il ripasso dei concetti chiave di corsi universitari.<br>Progetto accademico per il corso Paradigmi di Programmazione e Sviluppo (PPS).
  -
    scope:
      path: "en"
    values:
      description: Application to gamify the review of the main topics of university courses.<br>Academic Project for Paradigms of Programming and Development (PPS) Course.
